### ISSUE TITLE
2.7.6 with jruby 9.1.8.0 does not work with memcached 1.4.4 and 1.4.36

### ISSUE THREAD

**Issue by wedgemartin** [petergoldstein/dalli#653]
[root@nanonano:1 memcached-1.4.36]# ./memcached -p 11211 -u memcached -m 2048 -c 1024 -vvvvvvvvv

jruby-9.1.8.0 :022 > client = Dalli::Client.new('127.0.0.1:11211')
 => #<Dalli::Client:0x42c9b1ee @servers=["127.0.0.1:11211"], @ring=nil, @options={}> 
jruby-9.1.8.0 :023 > client.set('abc', 12345)
 => 72057594037927936   # Where this big int comes from i have no clue.

#### in memcached output i see

36: going from conn_parse_cmd to conn_nread
<36 SET abc Value len is 6
> NOT FOUND abc
>36 Writing bin response:
>36   0x81 0x01 0x00 0x00
>36   0x00 0x00 0x00 0x00
>36   0x00 0x00 0x00 0x00
>36   0x00 0x00 0x00 0x00
>36   0x00 0x00 0x00 0x00
>36   0x00 0x00 0x00 0x01

#### So it set the value..   Now try to fetch it:

jruby-9.1.8.0 :024 > client.get('abc')
Dalli::RingError: No server available
	from /home/ade/.rvm/gems/jruby-9.1.8.0@enade/gems/dalli-2.7.6/lib/dalli/ring.rb:45:in `server_for_key'
	from /home/ade/.rvm/gems/jruby-9.1.8.0@enade/gems/dalli-2.7.6/lib/dalli/client.rb:361:in `perform'
	from /home/ade/.rvm/gems/jruby-9.1.8.0@enade/gems/dalli-2.7.6/lib/dalli/client.rb:58:in `get'
	from (irb):24:in `<eval>'
	from org/jruby/RubyKernel.java:1000:in `eval'
	from org/jruby/RubyKernel.java:1298:in `loop'
	from org/jruby/RubyKernel.java:1120:in `catch'
	from org/jruby/RubyKernel.java:1120:in `catch'
	from /home/ade/.rvm/gems/jruby-9.1.8.0@enade/gems/railties-5.0.2/lib/rails/commands/console.rb:65:in `start'
	from /home/ade/.rvm/gems/jruby-9.1.8.0@enade/gems/railties-5.0.2/lib/rails/commands/console_helper.rb:9:in `start'
	from /home/ade/.rvm/gems/jruby-9.1.8.0@enade/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:78:in `console'
	from /home/ade/.rvm/gems/jruby-9.1.8.0@enade/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /home/ade/.rvm/gems/jruby-9.1.8.0@enade/gems/railties-5.0.2/lib/rails/commands.rb:18:in `<main>'
	from org/jruby/RubyKernel.java:961:in `require'
	from bin/rails:4:in `<main>'

####   Error. Yet on the memcached side, things worked as expected:

<36 GET abc
> FOUND KEY abc
>36 Writing bin response:
>36   0x81 0x00 0x00 0x00
>36   0x04 0x00 0x00 0x00
>36   0x00 0x00 0x00 0x0a
>36   0x00 0x00 0x00 0x00
>36   0x00 0x00 0x00 0x00
>36   0x00 0x00 0x00 0x00

**Comment by wedgemartin** [comment]
###Some more info:

jruby-9.1.8.0 :007 > client.inspect
 => "#<Dalli::Client:0x13809363 @servers=[\"127.0.0.1:11211\"], @ring=#<Dalli::Ring:0x49de1505 @failover=true, @continuum=nil, @servers=[#<Dalli::Server:0x29e3c28 @last_down_at=2017-04-03 15:48:58 +0000, @socket_type=:tcp, @hostname=\"127.0.0.1\", @options={:down_retry_delay=>1, :socket_timeout=>0.5, :socket_max_failures=>2, :socket_failure_delay=>0.01, :value_max_bytes=>1048576, :compressor=>Dalli::Compressor, :compression_min_size=>1024, :compression_max_size=>false, :serializer=>Marshal, :username=>nil, :password=>nil, :keepalive=>true, :sndbuf=>nil, :rcvbuf=>nil}, @error=\"NoMethodError\", @fail_count=0, @lock=#<Monitor:0x7146c6ea @mon_mutex=#<Mutex:0xa5d23c9>, @mon_count=0, @mon_owner=nil>, @down_at=2017-04-03 15:48:58 +0000, @pid=nil, @weight=1, @version=\"1.4.36\", @inprogress=false, @port=11211, @sock=nil, @msg=\"undefined method `call' for nil:NilClass\\nDid you mean?  caller\">]>, @options={}>"

**Comment by wedgemartin** [comment]
Have also tried unsuccessfully with jruby versions 9.0.5.0 and 9.1.7.0

**Comment by wedgemartin** [comment]
A little more info. Think this is a threading issue.   I've modified the server_for_key method in the dally gem which I see gets called twice.  The first time through, server.alive? returns true, the second time through it returns 'false'

    def server_for_key(key)
      puts "  SERVER FOR KEY: #{key}"
      if @continuum
        puts "continuum..."
        hkey = hash_for(key)
        20.times do |try|
          entryidx = binary_search(@continuum, hkey)
          server = @continuum[entryidx].server
          return server if server.alive?
          break unless @failover
          hkey = hash_for("#{try}#{key}")
        end
      else
        puts "not continuum..."
        server = @servers.first
        puts "  SERVER: #{server.inspect}"
        puts "  SERVER ALIVE?: #{server.alive?}" if server
        return server if server && server.alive?
      end

      raise Dalli::RingError, "No server available"
    end

Yields:

jruby-9.1.8.0 :014 >   client.get('abc')
  SERVER FOR KEY: abc
not continuum...
  SERVER: #<Dalli::Server:0x7b9fea11 @last_down_at=2017-04-03 16:42:04 +0000, @socket_type=:tcp, @hostname="127.0.0.1", @options={:down_retry_delay=>1, :socket_timeout=>0.5, :socket_max_failures=>2, :socket_failure_delay=>0.01, :value_max_bytes=>1048576, :compressor=>Dalli::Compressor, :compression_min_size=>1024, :compression_max_size=>false, :serializer=>Marshal, :username=>nil, :password=>nil, :keepalive=>true, :sndbuf=>nil, :rcvbuf=>nil}, @error="NoMethodError", @fail_count=0, @lock=#<Monitor:0x56e78538 @mon_mutex=#<Mutex:0x731fae>, @mon_count=0, @mon_owner=nil>, @down_at=2017-04-03 16:42:04 +0000, @pid=nil, @weight=1, @version="1.4.4", @inprogress=false, @port=11211, @sock=nil, @msg="undefined method `call' for nil:NilClass\nDid you mean?  caller">
  SERVER ALIVE?: true
  SERVER FOR KEY: abc
not continuum...
  SERVER: #<Dalli::Server:0x7b9fea11 @last_down_at=2017-04-03 16:42:08 +0000, @socket_type=:tcp, @hostname="127.0.0.1", @options={:down_retry_delay=>1, :socket_timeout=>0.5, :socket_max_failures=>2, :socket_failure_delay=>0.01, :value_max_bytes=>1048576, :compressor=>Dalli::Compressor, :compression_min_size=>1024, :compression_max_size=>false, :serializer=>Marshal, :username=>nil, :password=>nil, :keepalive=>true, :sndbuf=>nil, :rcvbuf=>nil}, @error="NoMethodError", @fail_count=0, @lock=#<Monitor:0x56e78538 @mon_mutex=#<Mutex:0x731fae>, @mon_count=0, @mon_owner=nil>, @down_at=2017-04-03 16:42:08 +0000, @pid=nil, @weight=1, @version="1.4.4", @inprogress=false, @port=11211, @sock=nil, @msg="undefined method `call' for nil:NilClass\nDid you mean?  caller">
  SERVER ALIVE?: false
Dalli::RingError: No server available
	from /home/ade/.rvm/gems/jruby-9.1.8.0@enade/gems/dalli-2.7.6/lib/dalli/ring.rb:50:in `server_for_key'
	from /home/ade/.rvm/gems/jruby-9.1.8.0@enade/gems/dalli-2.7.6/lib/dalli/client.rb:361:in `perform'
	from /home/ade/.rvm/gems/jruby-9.1.8.0@enade/gems/dalli-2.7.6/lib/dalli/client.rb:58:in `get'
	from (irb):14:in `<eval>'
	from org/jruby/RubyKernel.java:1000:in `eval'
	from org/jruby/RubyKernel.java:1298:in `loop'
	from org/jruby/RubyKernel.java:1120:in `catch'
	from org/jruby/RubyKernel.java:1120:in `catch'
	from /home/ade/.rvm/gems/jruby-9.1.8.0@enade/gems/railties-5.0.2/lib/rails/commands/console.rb:65:in `start'
	from /home/ade/.rvm/gems/jruby-9.1.8.0@enade/gems/railties-5.0.2/lib/rails/commands/console_helper.rb:9:in `start'
	from /home/ade/.rvm/gems/jruby-9.1.8.0@enade/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:78:in `console'
	from /home/ade/.rvm/gems/jruby-9.1.8.0@enade/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /home/ade/.rvm/gems/jruby-9.1.8.0@enade/gems/railties-5.0.2/lib/rails/commands.rb:18:in `<main>'
	from org/jruby/RubyKernel.java:961:in `require'
	from bin/rails:4:in `<main>'

**Comment by wedgemartin** [comment]
Just using the client from an IRB session works fine, so it's something else getting in the way, maybe something in ActiveRecord? Using rails 5.0.2

**Comment by wedgemartin** [comment]
Works with active support etc vs 4.2.4, dies in 5.x

**Comment by petergoldstein** [comment]
@wedgemartin Are you still having this issue with more recent JRubys / Rails versions?

**Comment by wedgemartin** [comment]
Nope!  Seems like it’s cleared up.

Thanks for the follow up!

**Comment by petergoldstein** [comment]
Thanks.  Closing.
