### ISSUE TITLE
undefined method `with` error for Dalli::Client after updating to 3.0 in Rails

### ISSUE THREAD

**Issue by clinejj** [petergoldstein/dalli#791]
We're using Rails 6.1.4.1, and after updating to Dalli 3.0 today we started getting the following error:

```sh
 NoMethodError (undefined method `with' for #<Dalli::Client:0x0000 @servers=["host:port"], @options={:username=>"hidden", :password=>"hidden"}, @ring=nil>):
   
 activesupport (6.1.4.1) lib/active_support/cache/mem_cache_store.rb:157:in `block in write_entry'
 activesupport (6.1.4.1) lib/active_support/cache/mem_cache_store.rb:206:in `rescue_error_with'
 activesupport (6.1.4.1) lib/active_support/cache/mem_cache_store.rb:155:in `write_entry'
 activesupport (6.1.4.1) lib/active_support/cache/strategy/local_cache.rb:165:in `write_entry'
 activesupport (6.1.4.1) lib/active_support/cache/mem_cache_store.rb:40:in `write_entry'
```

We're using the recommended Rails cache configuration:
```rb
config.cache_store = :mem_cache_store, ENV['MEMCACHED_SERVERS'].split(','), { :username => ENV['MEMCACHED_USERNAME'], :password => ENV['MEMCACHED_PASSWORD'] }
```

This appears to be due to the removed `Dalli::Client#with` method (commit [here](https://github.com/petergoldstein/dalli/commit/c6fc3101bdbf00357f649f2ddd0cf93fe50f060a#diff-a326ee7acf56937d92cdeeb4b920547a89162170aab2ad32391200ad1b4c3638)), which Rails still relies on for all the cache calls in [ActiveSupport::Cache::MemCacheStore](https://github.com/rails/rails/blob/main/activesupport/lib/active_support/cache/mem_cache_store.rb#L87) (which gets cached onto the `@data` object in the class).

I'm not sure if this is an intentional change that wasn't as clearly noted in the changelog, and thus Rails must be updated, or if there's a desire to preserve support for current versions of Rails (including the main branch).

This can be patched by adding the method back in an initializer, eg `config/initializers/dalli_client_patch.rb`

```rb
module Dalli
  class Client
    def with
      yield self
    end
  end
end
```

**Comment by clinejj** [comment]
@ryanb good eye, will close this
